/**
 * Provenance Metadata Types
 *
 * Defines structures for tracking origin and trust level of context items.
 *
 * Security: V3.1 - Context provenance metadata (Round 2 audit, CVSS 7.5)
 * Audit: Round 2 V3 - Context provenance gaps enable injection attacks
 */

import { createHash } from 'crypto';

/**
 * Trust levels for context sources
 *
 * - high: Verified, signed content from authenticated sources
 * - medium: Unverified but from known sources (e.g., unsigned database entries)
 * - low: External or untrusted sources (e.g., web content, user input)
 */
export enum TrustLevel {
  High = 'high',
  Medium = 'medium',
  Low = 'low',
}

/**
 * Source types for context items
 *
 * Categorizes where context originated for provenance tracking.
 */
export enum SourceType {
  Memory = 'memory',           // Recall from memory.db
  Broadcast = 'broadcast',     // Swarm broadcast from coordination.db
  File = 'file',              // File read from filesystem
  Session = 'session',         // Session metadata from sessions.db
  Agent = 'agent',            // Agent output or status
  Hook = 'hook',              // Generated by a hook
  User = 'user',              // Direct user input
  External = 'external',       // External sources (web, API)
}

/**
 * Provenance metadata for context items
 *
 * Attached to all context injected into Claude's prompts to enable
 * trust-based filtering and audit trails.
 */
export interface ProvenanceMetadata {
  /** Session that created or fetched this context */
  session_id: string;

  /** Agent that created this context (if applicable) */
  agent_id: string | null;

  /** Unix timestamp of creation/fetch */
  timestamp: number;

  /** Trust level based on verification and source */
  trust_level: TrustLevel;

  /** Type of source this context came from */
  source_type: SourceType;

  /** SHA-256 hash of content for integrity verification */
  content_hash: string;

  /** HMAC-SHA256 signature (if available from database) */
  signature?: string;

  /** Optional additional metadata */
  metadata?: Record<string, unknown>;
}

/**
 * Context item with provenance metadata
 *
 * Wrapper for any context content with attached provenance.
 */
export interface ProvenancedContext<T = string> {
  /** The actual content */
  content: T;

  /** Provenance metadata */
  provenance: ProvenanceMetadata;
}

/**
 * Compute SHA-256 hash of content for integrity verification
 *
 * @param content - Content to hash (string or serializable object)
 * @returns Hex-encoded SHA-256 hash
 */
export function computeContentHash(content: unknown): string {
  const contentStr = typeof content === 'string'
    ? content
    : JSON.stringify(content);

  return createHash('sha256')
    .update(contentStr, 'utf8')
    .digest('hex');
}

/**
 * Create provenance metadata for a context item
 *
 * @param options - Provenance metadata options
 * @returns Complete provenance metadata object
 */
export function createProvenance(options: {
  session_id: string;
  agent_id?: string | null;
  timestamp?: number;
  trust_level: TrustLevel;
  source_type: SourceType;
  content: unknown;
  signature?: string;
  metadata?: Record<string, unknown>;
}): ProvenanceMetadata {
  return {
    session_id: options.session_id,
    agent_id: options.agent_id || null,
    timestamp: options.timestamp || Date.now(),
    trust_level: options.trust_level,
    source_type: options.source_type,
    content_hash: computeContentHash(options.content),
    signature: options.signature,
    metadata: options.metadata,
  };
}

/**
 * Wrap content with provenance metadata
 *
 * @param content - Content to wrap
 * @param provenance - Provenance metadata
 * @returns Provenance-wrapped content
 */
export function withProvenance<T>(
  content: T,
  provenance: ProvenanceMetadata
): ProvenancedContext<T> {
  return {
    content,
    provenance,
  };
}

/**
 * Determine trust level from database signature status
 *
 * @param hasSignature - Whether entry has a signature field
 * @param signatureValid - Whether signature verification passed (if checked)
 * @param sourceType - Type of source
 * @returns Appropriate trust level
 */
export function determineTrustLevel(
  hasSignature: boolean,
  signatureValid: boolean | null,
  sourceType: SourceType
): TrustLevel {
  // Signed and verified = high trust
  if (hasSignature && signatureValid === true) {
    return TrustLevel.High;
  }

  // Unsigned database entries = medium trust (known source, no verification)
  if (sourceType === SourceType.Memory ||
      sourceType === SourceType.Broadcast ||
      sourceType === SourceType.Session ||
      sourceType === SourceType.Agent) {
    return TrustLevel.Medium;
  }

  // External sources, unsigned, or failed verification = low trust
  return TrustLevel.Low;
}

/**
 * Validate provenance metadata structure
 *
 * @param provenance - Provenance metadata to validate
 * @returns true if valid, false otherwise
 */
export function isValidProvenance(provenance: unknown): provenance is ProvenanceMetadata {
  if (!provenance || typeof provenance !== 'object') {
    return false;
  }

  const p = provenance as Partial<ProvenanceMetadata>;

  return (
    typeof p.session_id === 'string' &&
    p.session_id.length > 0 &&
    (p.agent_id === null || typeof p.agent_id === 'string') &&
    typeof p.timestamp === 'number' &&
    p.timestamp > 0 &&
    Object.values(TrustLevel).includes(p.trust_level as TrustLevel) &&
    Object.values(SourceType).includes(p.source_type as SourceType) &&
    typeof p.content_hash === 'string' &&
    p.content_hash.length === 64 // SHA-256 hex = 64 chars
  );
}

/**
 * Format provenance metadata for display in context
 *
 * @param provenance - Provenance metadata
 * @param verbose - Include full details (default: false)
 * @returns Formatted provenance string
 */
export function formatProvenance(
  provenance: ProvenanceMetadata,
  verbose: boolean = false
): string {
  const timestamp = new Date(provenance.timestamp).toISOString();
  const agentStr = provenance.agent_id ? ` agent=${provenance.agent_id}` : '';

  if (verbose) {
    return [
      `[PROVENANCE]`,
      `  source=${provenance.source_type}`,
      `  trust=${provenance.trust_level}`,
      `  session=${provenance.session_id}${agentStr}`,
      `  time=${timestamp}`,
      `  hash=${provenance.content_hash.slice(0, 16)}...`,
      provenance.signature ? `  signed=yes` : `  signed=no`,
    ].join('\n');
  }

  return `[${provenance.source_type}:${provenance.trust_level}@${provenance.session_id}${agentStr}]`;
}

/**
 * Filter context items by minimum trust level
 *
 * @param items - Provenance-wrapped context items
 * @param minTrustLevel - Minimum required trust level
 * @returns Filtered items meeting trust requirement
 */
export function filterByTrust<T>(
  items: ProvenancedContext<T>[],
  minTrustLevel: TrustLevel
): ProvenancedContext<T>[] {
  const trustOrder = {
    [TrustLevel.High]: 3,
    [TrustLevel.Medium]: 2,
    [TrustLevel.Low]: 1,
  };

  const minLevel = trustOrder[minTrustLevel];

  return items.filter(item =>
    trustOrder[item.provenance.trust_level] >= minLevel
  );
}

/**
 * Sort context items by trust level (high to low)
 *
 * @param items - Provenance-wrapped context items
 * @returns Sorted items (high trust first)
 */
export function sortByTrust<T>(
  items: ProvenancedContext<T>[]
): ProvenancedContext<T>[] {
  const trustOrder = {
    [TrustLevel.High]: 3,
    [TrustLevel.Medium]: 2,
    [TrustLevel.Low]: 1,
  };

  return [...items].sort((a, b) =>
    trustOrder[b.provenance.trust_level] - trustOrder[a.provenance.trust_level]
  );
}
