/**
 * Trust Tier Classification System
 *
 * Implements rules for assigning and managing trust levels for context items
 * based on provenance, age, verification status, and source type.
 *
 * Security: V3.2 - Trust tier system (Round 2 audit, CVSS 7.5)
 * Audit: Round 2 V3 - Context provenance gaps enable injection attacks
 */

import type { ProvenanceMetadata, ProvenancedContext } from './provenance-types.js';
import { TrustLevel, SourceType } from './provenance-types.js';

/**
 * Trust tier configuration
 *
 * Defines thresholds and policies for trust level assignment.
 */
export interface TrustTierConfig {
  /** Maximum age (milliseconds) before trust degrades */
  maxAgeMs: {
    high: number;    // High trust expires after this
    medium: number;  // Medium trust expires after this
  };

  /** Whether to require signatures for high trust */
  requireSignatureForHigh: boolean;

  /** Whether to allow external sources */
  allowExternalSources: boolean;

  /** Minimum trust level for context inclusion (null = allow all) */
  minTrustLevel: TrustLevel | null;
}

/**
 * Default trust tier configuration
 */
export const DEFAULT_TRUST_CONFIG: TrustTierConfig = {
  maxAgeMs: {
    high: 7 * 24 * 60 * 60 * 1000,    // 7 days
    medium: 30 * 24 * 60 * 60 * 1000, // 30 days
  },
  requireSignatureForHigh: true,
  allowExternalSources: true,
  minTrustLevel: null, // Accept all trust levels by default
};

/**
 * Source-specific base trust levels
 *
 * Default trust level for each source type before verification.
 */
const SOURCE_BASE_TRUST: Record<SourceType, TrustLevel> = {
  [SourceType.Memory]: TrustLevel.Medium,      // Database, but unsigned
  [SourceType.Broadcast]: TrustLevel.Medium,   // Database, but unsigned
  [SourceType.File]: TrustLevel.Medium,        // Filesystem, trusted path
  [SourceType.Session]: TrustLevel.Medium,     // Database, but unsigned
  [SourceType.Agent]: TrustLevel.Medium,       // Known source, but unsigned
  [SourceType.Hook]: TrustLevel.High,          // Generated by verified hook
  [SourceType.User]: TrustLevel.High,          // Direct user input
  [SourceType.External]: TrustLevel.Low,       // External, unverified
};

/**
 * Compute trust level for a context item based on all factors
 *
 * Considers:
 * - Source type
 * - Signature presence and validity
 * - Age of content
 * - Current trust tier configuration
 *
 * @param provenance - Provenance metadata
 * @param signatureValid - Whether signature verification passed (null if not checked)
 * @param config - Trust tier configuration
 * @returns Computed trust level
 */
export function computeTrustLevel(
  provenance: ProvenanceMetadata,
  signatureValid: boolean | null = null,
  config: TrustTierConfig = DEFAULT_TRUST_CONFIG
): TrustLevel {
  const now = Date.now();
  const age = now - provenance.timestamp;

  // Start with base trust for source type
  let trust = SOURCE_BASE_TRUST[provenance.source_type];

  // Upgrade to high if signature is valid
  if (provenance.signature && signatureValid === true) {
    trust = TrustLevel.High;
  }

  // Downgrade if signature required but missing
  if (config.requireSignatureForHigh && !provenance.signature && trust === TrustLevel.High) {
    trust = TrustLevel.Medium;
  }

  // Age-based degradation
  if (trust === TrustLevel.High && age > config.maxAgeMs.high) {
    trust = TrustLevel.Medium;
  }
  if (trust === TrustLevel.Medium && age > config.maxAgeMs.medium) {
    trust = TrustLevel.Low;
  }

  // External sources always low trust unless explicitly verified
  if (provenance.source_type === SourceType.External && signatureValid !== true) {
    trust = TrustLevel.Low;
  }

  return trust;
}

/**
 * Check if a context item meets minimum trust requirements
 *
 * @param provenance - Provenance metadata
 * @param config - Trust tier configuration
 * @returns true if item meets requirements
 */
export function meetsTrustRequirements(
  provenance: ProvenanceMetadata,
  config: TrustTierConfig = DEFAULT_TRUST_CONFIG
): boolean {
  // No minimum requirement = accept all
  if (!config.minTrustLevel) {
    return true;
  }

  // Reject external sources if not allowed
  if (!config.allowExternalSources && provenance.source_type === SourceType.External) {
    return false;
  }

  const trustOrder = {
    [TrustLevel.High]: 3,
    [TrustLevel.Medium]: 2,
    [TrustLevel.Low]: 1,
  };

  return trustOrder[provenance.trust_level] >= trustOrder[config.minTrustLevel];
}

/**
 * Filter context items by trust requirements
 *
 * @param items - Provenance-wrapped context items
 * @param config - Trust tier configuration
 * @returns Filtered items meeting trust requirements
 */
export function filterByTrustRequirements<T>(
  items: ProvenancedContext<T>[],
  config: TrustTierConfig = DEFAULT_TRUST_CONFIG
): ProvenancedContext<T>[] {
  return items.filter(item => meetsTrustRequirements(item.provenance, config));
}

/**
 * Update provenance trust level based on verification result
 *
 * Call this after verifying a signature to upgrade/downgrade trust.
 *
 * @param provenance - Provenance metadata to update
 * @param signatureValid - Signature verification result
 * @param config - Trust tier configuration
 * @returns Updated provenance metadata
 */
export function updateTrustLevel(
  provenance: ProvenanceMetadata,
  signatureValid: boolean,
  config: TrustTierConfig = DEFAULT_TRUST_CONFIG
): ProvenanceMetadata {
  return {
    ...provenance,
    trust_level: computeTrustLevel(provenance, signatureValid, config),
  };
}

/**
 * Assign salience weight based on trust level
 *
 * Higher trust = higher salience (more prominent in context).
 * Used for context ranking and prioritization.
 *
 * @param trustLevel - Trust level
 * @returns Salience weight (0.0 - 1.0)
 */
export function getSalienceWeight(trustLevel: TrustLevel): number {
  switch (trustLevel) {
    case TrustLevel.High:
      return 1.0;   // Full salience
    case TrustLevel.Medium:
      return 0.6;   // Reduced salience
    case TrustLevel.Low:
      return 0.3;   // Minimal salience
    default:
      return 0.0;
  }
}

/**
 * Sort context items by trust and recency
 *
 * Primary sort: trust level (high to low)
 * Secondary sort: timestamp (recent to old)
 *
 * @param items - Provenance-wrapped context items
 * @returns Sorted items (high trust, recent first)
 */
export function sortByTrustAndRecency<T>(
  items: ProvenancedContext<T>[]
): ProvenancedContext<T>[] {
  const trustOrder = {
    [TrustLevel.High]: 3,
    [TrustLevel.Medium]: 2,
    [TrustLevel.Low]: 1,
  };

  return [...items].sort((a, b) => {
    // Primary: trust level
    const trustDiff = trustOrder[b.provenance.trust_level] - trustOrder[a.provenance.trust_level];
    if (trustDiff !== 0) {
      return trustDiff;
    }

    // Secondary: timestamp (recent first)
    return b.provenance.timestamp - a.provenance.timestamp;
  });
}

/**
 * Partition context items by trust level
 *
 * Separates items into high/medium/low trust buckets for processing.
 *
 * @param items - Provenance-wrapped context items
 * @returns Object with high/medium/low arrays
 */
export function partitionByTrust<T>(
  items: ProvenancedContext<T>[]
): {
  high: ProvenancedContext<T>[];
  medium: ProvenancedContext<T>[];
  low: ProvenancedContext<T>[];
} {
  const high: ProvenancedContext<T>[] = [];
  const medium: ProvenancedContext<T>[] = [];
  const low: ProvenancedContext<T>[] = [];

  for (const item of items) {
    switch (item.provenance.trust_level) {
      case TrustLevel.High:
        high.push(item);
        break;
      case TrustLevel.Medium:
        medium.push(item);
        break;
      case TrustLevel.Low:
        low.push(item);
        break;
    }
  }

  return { high, medium, low };
}

/**
 * Get trust level summary statistics
 *
 * @param items - Provenance-wrapped context items
 * @returns Count and percentage for each trust level
 */
export function getTrustStatistics<T>(
  items: ProvenancedContext<T>[]
): {
  total: number;
  high: { count: number; percent: number };
  medium: { count: number; percent: number };
  low: { count: number; percent: number };
} {
  const total = items.length;
  if (total === 0) {
    return {
      total: 0,
      high: { count: 0, percent: 0 },
      medium: { count: 0, percent: 0 },
      low: { count: 0, percent: 0 },
    };
  }

  const partitioned = partitionByTrust(items);

  return {
    total,
    high: {
      count: partitioned.high.length,
      percent: (partitioned.high.length / total) * 100,
    },
    medium: {
      count: partitioned.medium.length,
      percent: (partitioned.medium.length / total) * 100,
    },
    low: {
      count: partitioned.low.length,
      percent: (partitioned.low.length / total) * 100,
    },
  };
}

/**
 * Create a trust-aware context summary
 *
 * Generates a formatted summary showing trust distribution.
 *
 * @param items - Provenance-wrapped context items
 * @returns Formatted summary string
 */
export function formatTrustSummary<T>(
  items: ProvenancedContext<T>[]
): string {
  const stats = getTrustStatistics(items);

  if (stats.total === 0) {
    return 'No context items';
  }

  return [
    `Trust Distribution (${stats.total} items):`,
    `  High:   ${stats.high.count.toString().padStart(3)} (${stats.high.percent.toFixed(1)}%)`,
    `  Medium: ${stats.medium.count.toString().padStart(3)} (${stats.medium.percent.toFixed(1)}%)`,
    `  Low:    ${stats.low.count.toString().padStart(3)} (${stats.low.percent.toFixed(1)}%)`,
  ].join('\n');
}
